spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8157

logging:
  file:
    name: logs/stumanagement.log
    path: stumanagement
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























